name: Deploy Application

on:
  push:
    branches:
      - main

env:
    service_name: laravel-app

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: PHP Composer Install
        run: cd my-app && composer install

    #   - uses: php-actions/phpunit@v3
    #     with:
    #       working-dir: ./app
    
    #   - name: Build docker image
    #     run: docker build -t ${{ env.service_name }} ./app
    
    #   - name: Run Trivy vulnerability scanner
    #     uses: aquasecurity/trivy-action@master
    #     with:
    #       image-ref: 'app:test'
    #       format: 'sarif'
    #       output: 'trivy-results.sarif'
    


